### ISSUE TITLE
Howto Build dfc for arm-linux-gnueabi

### ISSUE THREAD

**Issue by sebma** [Rolinh/dfc#14]
Hi,

I'd like to know how to build dfc for arm-linux-gnueabi ?

Can you help ?

**Comment by Rolinh** [comment]
Hi,

I assume you mean to cross-compile it for this architecture. In this case, it should be something like that (untested), assuming the compiler is installed and is `arm-linux-gnueabi-gcc`:
```
$ mkdir build && cd build
$ CC=arm-linux-gnueabi-gcc cmake ..
$ make
```
Of course, you can still follow the explanation in the README file about the various build options or use `ccmake` instead of `cmake` for a TUI interface.

**Comment by sebma** [comment]
Thank you :)

**Comment by Rolinh** [comment]
You're welcome.
